# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider 'docker' do |d|
    d.image = 'shipyard/agent'
    d.name = 'shipyard-agent'
    d.volumes = ['/var/run/docker.sock:/docker.sock']
    d.ports = ['4500:4500']
    d.env = {
      'IP' => '192.168.1.200',
      'URL' => 'http://192.168.1.200:8000' }
  end
end
