# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider 'docker' do |d|
    d.build_dir = '.'
    d.name = 'bdd01'
    d.ports = ['3306:3306']
    d.volumes = ['/var/lib/mysql']
  end
end

